#!/bin/bash

SERVICE=gammastep-refresh.service
TIMER=gammastep-refresh.timer

if systemctl --user is-active --quiet "$SERVICE"; then
  # KAPAT
  systemctl --user stop "$TIMER"
  systemctl --user stop "$SERVICE"
else
  # AÇ
  systemctl --user start "$SERVICE"
  systemctl --user enable --now "$TIMER"
fi
